freeze("$(PORT_DIR)/modules")
# Workspace modules (same layout as SEREN_S3/C3 manifests). Frozen from the dev
# worktree; static holds only the gzipped variants generated by tools/convert_statics.py.
# NOTE: do NOT also freeze "$(PORT_DIR)/seren_c6_modules" -- it duplicates app/* and
# breaks frozen_content.c with redefinition errors.
package("app", base_path="$(WORKSPACE_PATH)", files=[
    # "aioble_ota.py",
    # "ble.py",
    "commands.py",
    "config_server.py",
    "led.py",
    # "led_c3.py",
    "mcpwm.py",
    # "mic.py",
    "network_manager.py",
    # "ota_ble.py",
    "rotary.py",
    "run.py",
    "system.py",
    "version.py"
    ])
package("microdot", base_path="$(WORKSPACE_PATH)")
package("ota", base_path="$(WORKSPACE_PATH)")
package("static", base_path="$(WORKSPACE_PATH)", files=["index.py", "main.py", "style.py"])
freeze("$(WORKSPACE_PATH)", script="main.py")


include("$(MPY_DIR)/extmod/asyncio")

# Useful networking-related packages.
# require("bundle-networking")

# Require some micropython-lib modules.
require("aioespnow")
require("neopixel")
# BLE is optional at runtime (guarded import in app/run.py); aioble packages
# don't fit the 4 MiB OTA app partition, so they are not frozen for C6.
#require("aioble-server")
#require("aioble-peripheral")

