set(SDKCONFIG_DEFAULTS
    ${SDKCONFIG_DEFAULTS}
    boards/ESP32_GENERIC_S3/sdkconfig.flash_4m
)

set(MICROPY_FROZEN_MANIFEST ${MICROPY_BOARD_DIR}/manifest_4M.py)

list(APPEND MICROPY_DEF_BOARD
    MICROPY_HW_BOARD_NAME="4MB Flash"
)